# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Default
  demands:
   - agent.name -equals BEAST

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/MvcMovie.sln'
  project: '**/MvcMovie.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet Tool Installer'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'


- task: DotNetCoreCLI@2
  name: 'PublishToStaging'
  displayName: 'Publish to Staging'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  name: 'PublishToPipe'
  displayName: 'Publish to Pipe'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'MvcMovieProject'
    publishLocation: 'Container'
